//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "at_risk_accounts")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub user_address: String,
    pub last_updated_block_number: i32,
    #[sea_orm(column_type = "Float")]
    pub health_factor: f32,
    #[sea_orm(column_type = "Float")]
    pub total_collateral_value_in_usd: f32,
    #[sea_orm(column_type = "Float")]
    pub total_debt_value_in_usd: f32,
    pub leading_collateral_reserve: String,
    pub leading_debt_reserve: String,
    #[sea_orm(column_type = "Float")]
    pub leading_collateral_reserve_value: f32,
    #[sea_orm(column_type = "Float")]
    pub leading_debt_reserve_value: f32,
    pub timestamp: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
