//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

pub mod prelude;

pub mod at_risk_accounts;
pub mod healthy_accounts;
pub mod last_index_block;
pub mod liquidatable_accounts;
pub mod user_debt_collateral;
