//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "user_debt_collateral")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user_address: String,
    pub reserve_address: String,
    #[sea_orm(column_type = "Float")]
    pub amount: f32,
    pub is_collateral: bool,
    pub timestamp: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
